GRANT ALL PRIVILEGES ON DATABASE demo TO dbuser;
GRANT  ALL PRIVILEGES ON SCHEMA public TO dbuser;
GRANT  ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO dbuser;
GRANT  ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO dbuser;
GRANT  ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO dbuser;